version: '3.4'

services:
  event-sourcing.in.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - C:\db:C:\db
    ports:
      - "60000:80"
  event-sourcing.out.api:
    env_file: 
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - C:\db:C:\db
    ports:
      - "60001:80"
networks:
  default:
    external:
      name: nat