version: '3.4'

services:
  eventsourcing.in.api:
    image: ei8io/eventsourcing.in.api:0.1.4
    build:
      context: .
      dockerfile: ./main/Port.Adapter/In/Api/Dockerfile
  eventsourcing.out.api:
    image: ei8io/eventsourcing.out.api:0.1.4
    build:
      context: .
      dockerfile: ./main/Port.Adapter/Out/Api/Dockerfile