version: '3.4'

services:
  eventsourcing.in.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - /C/ei8/avatars/prod/sample:/C/db
      - /E/ei8/keys/sample:/C/keys
      
  eventsourcing.out.api:
    env_file: 
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - /C/ei8/avatars/prod/sample:/C/db
      - /E/ei8/keys/sample:/C/keys
networks:
    default:
        external:
            name: sample2_default